# Configuration file for package uintahtools

uintahpath: /home/hilde/trunk/opt/StandAlone/sus
porepressure_momentum:
- 0
- 0.02
- 0.08
- 0.10
- 0.15
- 0.2
- 0.55
terzaghi:
- 0.001
- 0.005
- 0.01
- 0.02
- 0.05
- 0.1
- 0.2
- 0.5
- 1.0
