# Configuration file for package uintahtools

uintahpath: /home/hilde/trunk/opt/StandAlone/sus
beam.deflection:
- 0.0
- 0.05
- 0.13
- 0.6
- 1.2
porepressure_momentum:
- 0
- 0.05
- 0.13
- 0.2
- 0.3
- 0.6
terzaghi:
- 0.001
- 0.005
- 0.01
- 0.02
- 0.05
- 0.1
- 0.2
- 0.5
- 1.0
